version: "3"
services:
  dev:
    build:
      dockerfile: "Dockerfile.dev"
    ports:
      - "5173:5173"
    develop:
      watch:
        - path: "."
          target: "/opt/react-ci"
          action: "sync"
          ignore:
            - "node_modules"
            - "dist"
  prod:
    build: "."
    environment:
      - "PORT=80"
    ports:
      - "80:80"